#!/bin/bash

set -u

function install_base_vm() {
    virt-install \
	--connect qemu:///system \
	--name maas \
	--ram 1024 \
	--cpu host \
	--vcpus 2 \
	--nographics \
	--disk pool=maas,size=20,bus=virtio,sparse=false \
	--network bridge=virbr0 \
	--location http://us.archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/ \
	--initrd-inject=preseeds/preseed.cfg \
	--extra-args="locale=en_US.UTF-8 console-setup/ask_detect=false keyboard-configuration/layoutcode=us file=file:/preseed.cfg vga=788 quiet console=tty0 utf8 console=ttyS0,115200" \
	--os-type=linux \
	--force \
	--noreboot
}


install_base_vm
